apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: i3nogdj2k-go-gitops
  description: This is GitOps manifest for i3nogdj2k-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: i3nogdj2k-go
    janus-idp.io/tekton: i3nogdj2k-go 
    backstage.io/kubernetes-id: i3nogdj2k-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:i3nogdj2k-go
